name: Build and Release Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write    # Needed to create/upload to Releases
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --windowed geolocator.py

      - name: Install GitHub CLI
        run: |
          choco install gh -y
          echo "C:\\Program Files\\GitHub CLI" >> $GITHUB_PATH

      - name: Create or Update Release and Upload EXE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest -y || true
          gh release create latest ./dist/geolocator.exe --title "Latest Build" --notes "Automated build of the latest commit from main." --prerelease --target ${{ github.sha }}
